<a href="https://colab.research.google.com/github/johsheldon/IMSE-541-Public/blob/main/HW5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import math
import random
import scipy
import statistics
import numpy as np
import scipy.stats
from scipy.special import comb
from scipy import stats
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.ticker import LinearLocator
import plotly.graph_objects as go
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp as mc
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [4]:
data = pd.read_csv('https://raw.githubusercontent.com/johsheldon/IMSE-541-Public/main/A6.%20Chap%2013.csv', sep=',', na_values=".")

data

     Run  a  b  c  d      I     II
0    (1) -1 -1 -1 -1   7037   6376
1      a  1 -1 -1 -1  14707  15219
2      b -1  1 -1 -1  11635  12089
3     ab  1  1 -1 -1  17273  17815
4      c -1 -1  1 -1  10403  10151
5     ac  1 -1  1 -1   4368   4098
6     bc -1  1  1 -1   9360   9253
7    abc  1  1  1 -1  13440  12923
8      d -1 -1 -1  1   8561   8951
9     ad  1 -1 -1  1  16867  17052
10    bd -1  1 -1  1  13876  13658
11   abd  1  1 -1  1  19824  19639
12    cd -1 -1  1  1  11846  12337
13   acd  1 -1  1  1   6125   5904
14   bcd -1  1  1  1  11190  10935
15  abcd  1  1  1  1  15653  15053

In [5]:
df=data #df means data frame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Run     16 non-null     object
 1   a       16 non-null     int64
 2   b       16 non-null     int64
 3   c       16 non-null     int64
 4   d       16 non-null     int64
 5   I       16 non-null     int64
 6   II      16 non-null     int64
dtypes: int64(6), object(1)
memory usage: 1.0+ KB

In [6]:
Xmain=df[['a', 'b', 'c', 'd']]
Xmain

    a  b  c  d
0  -1 -1 -1 -1
1   1 -1 -1 -1
2  -1  1 -1 -1
3   1  1 -1 -1
4  -1 -1  1 -1
5   1 -1  1 -1
6  -1  1  1 -1
7   1  1  1 -1
8  -1 -1 -1  1
9   1 -1 -1  1
10 -1  1 -1  1
11  1  1 -1  1
12 -1 -1  1  1
13  1 -1  1  1
14 -1  1  1  1
15  1  1  1  1

In [7]:
x1x2x3x4=df['a'] * df['b'] *df['c'] * df['d']
x1x2x3x4

0     1
1    -1
2    -1
3     1
4    -1
5     1
6     1
7    -1
8    -1
9     1
10    1
11   -1
12    1
13   -1
14   -1
15    1
dtype: int64

In [8]:
xx=Xmain.to_numpy()
poly= PolynomialFeatures(degree=3, interaction_only=True)
xxpd=pd.DataFrame(poly.fit_transform(xx), columns=['II', 'x1', 'x2', 'x3', 'x4','x1x2', 'x1x3', 'x1x4', 'x2x3', 'x2x4', 'x3x4', 'x1x2x3', 'x1x2x4', 'x1x3x4','x2x3x4'])
xxpd['x1x2x3x4']=x1x2x3x4
xxpd

,II,x1,x2,x3,x4,x1x2,x1x3,x1x4,x2x3,x2x4,x3x4,x1x2x3,x1x2x4,x1x3x4,x2x3x4,x1x2x3x4
0,1.0,-1.0,-1.0,-1.0,-1.0,1.0,1.0,1.0,1.0,1.0,1.0,-1.0,-1.0,-1.0,-1.0,1
1,1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0,1.0,1.0,1.0,1.0,1.0,-1.0,-1
2,1.0,-1.0,1.0,-1.0,-1.0,-1.0,1.0,1.0,-1.0,-1.0,1.0,1.0,1.0,-1.0,1.0,-1
3,1.0,1.0,1.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0,1.0,1.0,1
4,1.0,-1.0,-1.0,1.0,-1.0,1.0,-1.0,1.0,-1.0,1.0,-1.0,1.0,-1.0,1.0,1.0,-1
5,1.0,1.0,-1.0,1.0,-1.0,-1.0,1.0,-1.0,-1.0,1.0,-1.0,-1.0,1.0,-1.0,1.0,1
6,1.0,-1.0,1.0,1.0,-1.0,-1.0,-1.0,1.0,1.0,-1.0,-1.0,-1.0,1.0,1.0,-1.0,1
7,1.0,1.0,1.0,1.0,-1.0,1.0,1.0,-1.0,1.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1
8,1.0,-1.0,-1.0,-1.0,1.0,1.0,1.0,-1.0,1.0,-1.0,-1.0,-1.0,1.0,1.0,1.0,-1
9,1.0,1.0,-1.0,-1.0,1.0,-1.0,-1.0,1.0,1.0,-1.0,-1.0,1.0,-1.0,-1.0,1.0,1
10,1.0,-1.0,1.0,-1.0,1.0,-1.0,1.0,-1.0,-1.0,1.0,-1.0,1.0,-1.0,1.0,-1.0,1
11,1.0,1.0,1.0,-1.0,1.0,1.0,-1.0,1.0,-1.0,1.0,-1.0,-1.0,1.0,-1.0,-1.0,-1
12,1.0,-1.0,-1.0,1.0,1.0,1.0,-1.0,-1.0,-1.0,-1.0,1.0,1.0,1.0,-1.0,-1.0,1
13,1.0,1.0,-1.0,1.0,1.0,-1.0,1.0,1.0,-1.0,-1.0,1.0,-1.0,-1.0,1.0,-1.0,-1
14,1.0,-1.0,1.0,1.0,1.0,-1.0,-1.0,-1.0,1.0,1.0,1.0,-1.0,-1.0,-1.0,1.0,-1
15,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1

In [9]:
X=xxpd[['x1','x2','x3','x4','x1x2', 'x1x3', 'x1x4', 'x2x3', 'x2x4', 'x3x4']]
Y=df[['II']]
regr=LinearRegression()
regr.fit(X,Y)
Yhat=regr.predict(X)
Y=Y.to_numpy()
eij=Y-Yhat
print(eij)

[[-1805.9375]
 [ 1701.5625]
 [ 1736.5625]
 [-1632.1875]
 [ 1577.8125]
 [-1473.4375]
 [-1508.4375]
 [ 1404.0625]
 [-1382.9375]
 [ 1487.3125]
 [ 1452.3125]
 [-1556.6875]
 [ 1611.0625]
 [-1715.4375]
 [-1680.4375]
 [ 1784.8125]]

In [10]:
X=xxpd[['II','x1','x2','x3','x4','x1x2', 'x1x3', 'x1x4', 'x2x3', 'x2x4', 'x3x4']]
model = sm.OLS(Y, X)
res=model.fit()
print(res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.861
Model:                            OLS   Adj. R-squared:                  0.582
Method:                 Least Squares   F-statistic:                     3.086
Date:                Fri, 14 Oct 2022   Prob (F-statistic):              0.113
Time:                        05:08:30   Log-Likelihood:                -140.74
No. Observations:                  16   AIC:                             303.5
Df Residuals:                       5   BIC:                             312.0
Df Model:                          10
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
II          1.197e+04    715.441     16.725      0.000    1.01e+04    1.38e+04
x1          1497.0625    715.441      2.093      0.091    -342.037    3336.162
x2          1954.8125    715.441      2.732      0.041     115.713    3793.912
x3         -1884.0625    715.441     -2.633      0.046   -3723.162     -44.963
x4           975.3125    715.441      1.363      0.231    -863.787    2814.412
x1x2         939.8125    715.441      1.314      0.246    -899.287    2778.912
x1x3       -2084.3125    715.441     -2.913      0.033   -3923.412    -245.213
x1x4         -26.1875    715.441     -0.037      0.972   -1865.287    1812.912
x2x3           4.4375    715.441      0.006      0.995   -1834.662    1843.537
x2x4         -74.6875    715.441     -0.104      0.921   -1913.787    1764.412
x3x4           0.1875    715.441      0.000      1.000   -1838.912    1839.287
==============================================================================
Omnibus:                       26.993   Durbin-Watson:                   2.684
Prob(Omnibus):                  0.000   Jarque-Bera (JB):                2.596
Skew:                          -0.000   Prob(JB):                        0.273
Kurtosis:                       1.027   Cond. No.                         1.00
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

/usr/local/lib/python3.7/dist-packages/scipy/stats/stats.py:1542: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  "anyway, n=%i" % int(n))

In [20]:
# Reduced model with only factors A, D, and AD 
X=xxpd[['x1','x2','x3']]
Y=df[['II']]
regr2=LinearRegression()
regr2.fit(X,Y)
Yhat2=regr2.predict(X)
X2=xxpd[['II','x1','x2','x3']]
model2 = sm.OLS(Y, X2)
res2=model2.fit()
print(res2.summary())

#Yhat

                            OLS Regression Results
==============================================================================
Dep. Variable:                     II   R-squared:                       0.524
Model:                            OLS   Adj. R-squared:                  0.405
Method:                 Least Squares   F-statistic:                     4.397
Date:                Fri, 14 Oct 2022   Prob (F-statistic):             0.0263
Time:                        05:30:13   Log-Likelihood:                -150.57
No. Observations:                  16   AIC:                             309.1
Df Residuals:                      12   BIC:                             312.2
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
II          1.197e+04    853.639     14.017      0.000    1.01e+04    1.38e+04
x1          1497.0625    853.639      1.754      0.105    -362.858    3356.983
x2          1954.8125    853.639      2.290      0.041      94.892    3814.733
x3         -1884.0625    853.639     -2.207      0.048   -3743.983     -24.142
==============================================================================
Omnibus:                        0.064   Durbin-Watson:                   2.431
Prob(Omnibus):                  0.969   Jarque-Bera (JB):                0.294
Skew:                          -0.002   Prob(JB):                        0.863
Kurtosis:                       2.336   Cond. No.                         1.00
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

/usr/local/lib/python3.7/dist-packages/scipy/stats/stats.py:1542: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=16
  "anyway, n=%i" % int(n))

In [19]:
ydata0=[706, 764,780,761]
mse=statistics.variance(ydata0)
print(mse)

1040.9166666666667

In [15]:
model = ols('II ~ x1 + x2 + x3 + x4 + x1x2 + x1x3 + x1x4 + x2x3 + x2x4 + x3x4', data=df).fit()
aov_table = sm.stats.anova_lm(model, typ=2)
aov_table

PatsyError: ignored

In [21]:
z = data.values #data values without heading
sh_0, sh_1 = z.shape # dimension of the data matrix or table
x1, x2 = np.linspace(-1, 1, sh_1), np.linspace(-1, 1, sh_1)
#print(x1)
#print(x2)
#print(z)
z2=data[['x1','x2', 'x3']]
fig = go.Figure(data=[go.Surface(z=z2, x=x1, y=x2)])
fig.update_traces(contours_z=dict(show=True, usecolormap=True,
                                  highlightcolor="limegreen", project_z=True))
fig.update_layout(title='Surface Plot', autosize=False,
                  scene_camera_eye=dict(x=1.87, y=0.88, z=-0.64),
                  width=500, height=500,
                  margin=dict(l=65, r=50, b=65, t=90)
)
fig.update_layout(scene = dict(
                    xaxis_title='x1',
                    yaxis_title='x2',
                    zaxis_title='Surface Finish'),
                   )
fig.show()

KeyError: ignored